function task = generate_task_sumo(now, vehicle)
% GENERATE_TASK_SUMO  Generate a random computation task for a SUMO vehicle.
  types = {'PERCEPTION','PLANNING','CONTROL'};
  tp    = types{randi(3)};
  switch tp
    case 'PERCEPTION', cr=5+5*rand(); ds=20+10*rand(); dl=now+1.0; pr=3;
    case 'PLANNING',   cr=2+3*rand(); ds=5+5*rand();  dl=now+1.5; pr=2;
    case 'CONTROL',    cr=1+1*rand(); ds=1+1*rand();  dl=now+0.5; pr=3;
  end
  task = struct( ...
    'id',                       sprintf('V%d_T%d', vehicle.id, round(now*100)), ...
    'type',                     tp, ...
    'computationalRequirement', cr, ...
    'dataSize',                 ds, ...
    'generationTime',           now, ...
    'deadline',                 dl, ...
    'priority',                 pr, ...
    'status',                   'PENDING', ...
    'vehicleID',                vehicle.id ...
  );
end